name: putin
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rive:
  get_it:
  neon:
  http:
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  fonts:
    - family: TTNorms-Bold
      fonts:
        - asset: assets/fonts/TTNorms-Bold.ttf
  assets:
    - assets/animations/
    - assets/images/
